### ISSUE TITLE
Remove all compiler warnings

### ISSUE THREAD

**Issue by ilgrosso** [tmess567/SYNCOPE-809#12]
Eclipse reports several warnings, like as:
- ArrayList is a raw type. References to generic type ArrayList<E> should be parameterized

``` java
        private ArrayList children;

        public TreeParent(String name) {
            super(name);
            children = new ArrayList();
        }
```

should be instead

``` java
        private List<TreeObject> children;

        public TreeParent(String name) {
            super(name);
            children = new ArrayList<>();
        }
```

 *. Class is a raw type. References to generic type Class<T> should be parameterized
- ...

and so on.

**Comment by tmess567** [comment]
Done with [f0141f4d09b8a0a5e9d3df430608587758e706e2](https://github.com/tmess567/SYNCOPE-809/commit/f0141f4d09b8a0a5e9d3df430608587758e706e2)
