### ISSUE TITLE
Use adequate labels

### ISSUE THREAD

**Issue by ilgrosso** [tmess567/SYNCOPE-809#15]
At the moment, at the bottom of the editor window, it is shown:

![image](https://cloud.githubusercontent.com/assets/1064664/16393509/7048dece-3cb1-11e6-8821-722d92e2cbdc.png)

while it should be something like as `Text` / `HTML`

**Comment by tmess567** [comment]
Fixed with 4b5ffe2236aef5392600706b3f364ad25fb277c9

**Comment by ilgrosso** [comment]
Suggestion: instead of committing with message "Fixed String Values" and later manually closing issues with reference to commit, why don't you simply use a message like as "Fixed String Values - Fixes #15"?

See https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by tmess567** [comment]
Cool, Thanks.
Will do the next time.
