### ISSUE TITLE
Clean up root directory

### ISSUE THREAD

**Issue by ilgrosso** [tmess567/SYNCOPE-809#3]
1. remove `.settings` / `.classpath` / `.project` / `build.properties` from the git repo (it should be something you only need because you are working with this project with Eclipse, it should not be needed for building with Maven via CLI)
2. move `META-INF` under `src/main/resources/`
3. move `icons/` under `src/main/resources/`
4. please investigate if `contexts.xml` and `plugin.xml` are required to stay on the root folder or can be moved to `src/main/resources` as well

**Comment by tmess567** [comment]
Resolved 1. with commit 675944ea0e6009da69474bc309cce5a1c1b80f99

**Comment by tmess567** [comment]
Resolved 3. with commit 49c93de2072fd4ba855d9ea2e8c547c271008759

**Comment by tmess567** [comment]
Refactoring `plugin.xml` to `src/main/resources/` doesn't seem to be directly possible. Also, `plugin.xml` requires `META-INF` and `MANIFEST.MF` to be in the same directory, so that has to be in the root directory as well.
I will continue to look into it and ask other developers until I'm sure.

**Comment by ilgrosso** [comment]
Unfortunately I am not very expert about Eclipse, but I believe it is absolutely important that you take a look at [Tycho](http://www.eclipse.org/tycho/), given our requirements.

**Comment by tmess567** [comment]
I tried working with tycho today, but it lacks in documentation.
I tried to understand it, but even the demo builds fail. I've added the output [here](http://pastebin.com/hMj3kQQv).
I'll be subscribing to the their mailing list and see what I can get out of that.

**Comment by ilgrosso** [comment]
This error

```
org/eclipse/tycho/core/p2/P2ArtifactRepositoryLayout : Unsupported major.minor version 52.0
```

barely means you have some issues with JDK level compatibility: see more [here](http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0).

**Comment by ilgrosso** [comment]
Maybe the following docs can be of help:
- [Eclipse 4 Plug-in Development by Example.pdf](https://github.com/tmess567/SYNCOPE-809/files/289342/Eclipse.4.Plug-in.Development.by.Example.pdf)
- [Eclipse Tycho for building Eclipse Plug.pdf](https://github.com/tmess567/SYNCOPE-809/files/289341/Eclipse.Tycho.for.building.Eclipse.Plug.pdf)

**Comment by tmess567** [comment]
Thanks, I will read into it.

**Comment by tmess567** [comment]
The project has been modified to work in accordance with tycho now.
I believe this issue is solved as current root only includes necessary tycho folders, pom file and the Readme for github.

**Comment by ilgrosso** [comment]
Agree, we can close this issue and concentrate on adding features: we will come later to file organization once merging your code into the Apache Syncope codebase.
