### ISSUE TITLE
Can get rid of build.properties / .classpath?

### ISSUE THREAD

**Issue by ilgrosso** [tmess567/SYNCOPE-809#6]
Both `build.properties` and `.classpath` are currently checked in the source tree (under `bundles/org.apache.syncope.ide.eclipse.plugin`), and contain (static) dependency information.
Can they be safely removed?

If not, can they be dynamically generated from `pom.xml` as requested for #5?

**Comment by alexander-perucci** [comment]
`.classpath` file it is not important and you can remove it. The `build.properties` file has not to be removed and i don't know if there is a way to generate `build.properties` file using maven.

**Comment by ilgrosso** [comment]
Good for removing `.classpath`.
About `build.properties`, see my reply at #5.

**Comment by tmess567** [comment]
Will be working on making the build files dynamic today.
